### ISSUE TITLE
Unhandled exceptions

### ISSUE THREAD

**Issue by akrzos** [akrzos/gnocchi-status-collectd#2]
```
[2017-01-30 18:21:33] Unhandled python exception in read callback: Forbidden: Forbidden (HTTP 403)
[2017-01-30 18:21:33] Traceback (most recent call last):
[2017-01-30 18:21:33]   File "/usr/local/bin/collectd_gnocchi_status.py", line 25, in read
    status = gnocchi.status.get()
[2017-01-30 18:21:33]   File "/usr/lib/python2.7/site-packages/gnocchiclient/v1/status.py", line 21, in get
    return self._get(self.url + '?details=%s' % details).json()
[2017-01-30 18:21:33]   File "/usr/lib/python2.7/site-packages/gnocchiclient/v1/base.py", line 37, in _get
    return self.client.api.get(*args, **kwargs)
[2017-01-30 18:21:33]   File "/usr/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 187, in get
    return self.request(url, 'GET', **kwargs)
[2017-01-30 18:21:33]   File "/usr/lib/python2.7/site-packages/gnocchiclient/client.py", line 38, in request
    raise exceptions.from_response(resp, method)
[2017-01-30 18:21:33] Forbidden: Forbidden (HTTP 403)
```

**Comment by akrzos** [comment]
Fixed and re-uploaded to pypi.

**Comment by sbastani** [comment]
I am wondering how this is fixed. I get the error message all the time.

**Comment by akrzos** [comment]
> I am wondering how this is fixed. I get the error message all the time.

What is your exact issue? (Do you have a stacktrace or some details?)

The original issue here was that exceptions were not caught thus collectd backs off on its polling of the plugin.

**Comment by sbastani** [comment]
I was actually using basic authentication mode. To that end, I had defined a user for Gnocchi database and granted all privileges, but still could't retrieve some information such as gnocchi status. I just changed my user name to admin and every thing got fixed. Apologies for inconvenience.

**Comment by akrzos** [comment]
> Apologies for inconvenience.

No worries glad it is resolved 😃
