### ISSUE TITLE
Unable to install collectd-gnocchi-status 0.2.2

### ISSUE THREAD

**Issue by josue549** [akrzos/gnocchi-status-collectd#4]
Hello, 

I'm unable to install collectd-gnocchi-status 0.2.2 using pip. 

Please, find below the lines related to the error : 

```
  Current age based on date: 1029322
  Freshness lifetime from max-age: 31557600
  The response is "fresh", returning cached response
  31557600 > 1029322
  Using cached subprocess32-3.2.7.tar.gz
  Downloading from URL https://pypi.python.org/packages/b8/2f/49e53b0d0e94611a2dc624a1ad24d                                                                                                  41b6d94d0f1b0a078443407ea2214c2/subprocess32-3.2.7.tar.gz#md5=824c801e479d3e916879aae3e9c15                                                                                                  e16 (from https://pypi.python.org/simple/subprocess32/)
  Running setup.py (path:/tmp/pip-build-Ww_GDp/subprocess32/setup.py) egg_info for package                                                                                                   subprocess32
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/subprocess32.egg-info
    writing pip-egg-info/subprocess32.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/subprocess32.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/subprocess32.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/subprocess32.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/subprocess32.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.h'
    no previously-included directories found matching 'build'
    no previously-included directories found matching 'dist'
    no previously-included directories found matching '.hg*'
    writing manifest file 'pip-egg-info/subprocess32.egg-info/SOURCES.txt'
  Source in /tmp/pip-build-Ww_GDp/subprocess32 has version 3.2.7, which satisfies requireme                                                                                                  nt subprocess32 from https://pypi.python.org/packages/b8/2f/49e53b0d0e94611a2dc624a1ad24d41                                                                                                  b6d94d0f1b0a078443407ea2214c2/subprocess32-3.2.7.tar.gz#md5=824c801e479d3e916879aae3e9c15e1                                                                                                  6 (from cmd2>=0.6.7->cliff>1.16.0->gnocchiclient->collectd-gnocchi-status)
Installing collected packages: subprocess32, cmd2, unicodecsv, cliff, ujson, funcsigs, wrap                                                                                                  t, debtcollector, keystoneauth1, gnocchiclient, collectd-gnocchi-status
  Running setup.py install for subprocess32 ...     Running command /usr/bin/python2 -u -c                                                                                                   "import setuptools, tokenize;__file__='/tmp/pip-build-Ww_GDp/subprocess32/setup.py';f=getat                                                                                                  tr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(com                                                                                                  pile(code, __file__, 'exec'))" install --record /tmp/pip-xCVbu_-record/install-record.txt -                                                                                                  -single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    copying subprocess32.py -> build/lib.linux-x86_64-2.7
    running build_ext
    building '_posixsubprocess' extension
    creating build/temp.linux-x86_64-2.7
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptio                                                                                                  ns -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=gen                                                                                                  eric -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexce                                                                                                  ptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune                                                                                                  =generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c _posixsubprocess.c -                                                                                                  o build/temp.linux-x86_64-2.7/_posixsubprocess.o
    _posixsubprocess.c:3:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
error
Cleaning up...
  Removing source in /tmp/pip-build-Ww_GDp/collectd-gnocchi-status
  Removing source in /tmp/pip-build-Ww_GDp/ujson
  Removing source in /tmp/pip-build-Ww_GDp/cmd2
  Removing source in /tmp/pip-build-Ww_GDp/unicodecsv
  Removing source in /tmp/pip-build-Ww_GDp/wrapt
  Removing source in /tmp/pip-build-Ww_GDp/subprocess32
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Ww_GD                                                                                                  p/subprocess32/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace(                                                                                                  '\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xC                                                                                                  Vbu_-record/install-record.txt --single-version-externally-managed --compile" failed with e                                                                                                  rror code 1 in /tmp/pip-build-Ww_GDp/subprocess32/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/usr/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subproce                                                                                                  ss
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/                                                                                                  tmp/pip-build-Ww_GDp/subprocess32/setup.py';f=getattr(tokenize, 'open', open)(__file__);cod                                                                                                  e=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install -                                                                                                  -record /tmp/pip-xCVbu_-record/install-record.txt --single-version-externally-managed --com                                                                                                  pile" failed with error code 1 in /tmp/pip-build-Ww_GDp/subprocess32/
```

However I don't have any issue with the version 0.2.1

Please, don't hesitate to tell me if you need more information. 

Cheers,

**Comment by akrzos** [comment]
If you are on RHEL based OS try yum/dnf installing python-devel since it seems to be complaining about missing "Python.h".

**Comment by josue549** [comment]
Ah nice it worked thanks.
